spring:
  datasource:
    # 'product-db' ser√° el nombre del servicio en docker-compose
    url: jdbc:mysql://product-db:3306/product_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root