spring:
  datasource:
    url: jdbc:mysql://inventory-db:3306/inventory_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root

application:
  clients:
    # Nombre del servicio en docker-compose
    product-service-url: http://product-service:8081