spring:
  datasource:
    url: jdbc:mysql://purchase-db:3306/purchase_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root

application:
  clients:
    product-service-url: http://product-service:8081
    supplier-service-url: http://supplier-service:8082
    inventory-service-url: http://inventory-service:8083

